id: P002924
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 2021-12-17 10:28:44.102403
source_metadata:
  id: bdr:W3CN5192
  title: ལམ་གྱི་རོལ་དབྱངས།
  author: ''
  volumes:
    e89bd265a7af420d811eea2404a820b7:
      image_group_id: I3CN5194
      title: ''
      volume_number: 1
      total_pages: 167
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
